HyperMapperDemo/config/routes.rb
Tutorial::Application.routes.draw do
  resources :posts
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  
  resources :users

  resources :sessions, only: [:new, :create, :destroy]

end

HyperMapperDemo/app/models/post.rb
class Post
  include HyperMapper::Document
  
  attr_accessor :tag_string
  attr_accessible :title, :content, :user_id, :tag_string
  
  autogenerate_id
  attribute :title
  attribute :content
  attribute :user_id
  
  timestamps

  validates :title, presence: true
  validates :user_id, presence: true
  validates :content, presence: true

  belongs_to :user
  
  # we won't use this yet, but we want to generate this field
  # when we create the new space, so we'll add it now
  embeds_many :comments
  
  has_and_belongs_to_many :tags, through: :post_tags
  
  before_save :update_tags
  
  # and the function to update the tags
  def update_tags
    return unless tag_string
    new_tag_names = tag_string.split(",").map { |t| t.strip.downcase }
    current_tag_names = tags.collect(&:name)
    new_tag_names.each do |tag_name| 
      unless current_tag_names.include? tag_name
        tag = Tag.where(name: tag_name)[0]
        tag = Tag.create! name: tag_name unless tag
        self.tags << tag 
      end
    end
    tags.each { |t| (tags.remove t) unless (new_tag_names.include? t.name) }
  end  
  
  def tags_as_string
  	tags.collect(&:name).join(', ')
  end  
end

HyperMapperDemo/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_filter :redirect_unless_signed_in, 
                only: [:edit, :update, :new, :create, :destroy]  
  
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = current_user.posts.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = current_user.posts.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

HyperMapperDemo/app/helpers/posts_helper.rb
module PostsHelper
end

HyperMapperDemo/app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :tag_string, "Comma delimited tags" %><br />
    <%= f.text_field :tag_string, value: @post.tags_as_string %>
  </div>  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

HyperMapperDemo/app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

HyperMapperDemo/app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>User</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.user_id %></td>
    <td><%= post.content %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

HyperMapperDemo/app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

HyperMapperDemo/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>User:</b>
  <%= @post.user_id %>
</p>

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>

<p>
  <b>Tags:</b>
  <%= @post.tags_as_string %>
</p>


<%= link_to 'Back', posts_path %>

<% if signed_in? %>

  <% if current_user.id == @post.user_id %>
    <%= link_to 'Edit', edit_post_path(@post) %>
  <% end %>

  <%= form_for(:comment, url: post_comments_path(@post)) do |f| %>
    <%= f.text_field :text, autocomplete: :off %><br/>
    <%= f.hidden_field :post_id, value: @post.id %>
    <%= f.submit "Comment" %>
  <% end %>
  
<% end %>

<% @post.comments.each do |comment| %>
  <%= comment.text %> <br/>
<% end %>