hyper_blog/config/routes.rb
HyperBlog::Application.routes.draw do

  

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  
  get 'search' => 'posts#search'
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  
  root to: 'posts#index'

end

hyper_blog/app/views/layouts/application.html.erb
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <title>HyperMapper</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="wrapper">
	<div id="header-wrapper">
		<div id="header">
			<div id="logo">
        <h1>
          <%= image_tag 'hyperdex.png' %>
          <%= link_to 'HyperMapper', root_path %>
        </h1>
				<p>Template design by <a href="http://www.freecsstemplates.org/">FCT</a></p>
			</div>
			<div id="menu">
				<ul>
					<li><%= link_to raw("<span>Home</span>"), root_path %></li>
					<% if signed_in? %>
					  <li><%= link_to raw("<span>Post</span>"), new_post_path %></li>
					  <li><%= link_to raw("<span>My Account</span>"), edit_user_path(current_user) %></li>
            <li>
                  <%= link_to raw("<span>Sign out</span>"), session_path(id: current_user.session_id), method: :delete %>
                
            </li>
					<% else %>
					  <li><%= link_to raw("<span>Sign up</span>"), new_user_path %></li>
					  <li><%= link_to raw("<span>Sign in</span>"), new_session_path %></li>
					<% end %>
					
				</ul>
			</div>
		</div>
	</div>
	<!-- end #header -->
	<div id="page">
    <div id="content">
      <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %> 
      <%= yield %>
		</div>
		<div id="sidebar">
			<ul>
				<li>
					<h2>Search</h2>
					<div id="search" >
            <form method="get" action="<%= search_path %>">
							<div>
								<input type="text" name="query" id="search-text" value="" />
								<input type="submit" id="search-submit" value="GO" />
							</div>
						</form>
					</div>
					<div style="clear: both;">&nbsp;</div>
				</li>
				<li>
					<h2>Tags</h2>
					<p>
						<% @tags.each do |tag| %>
							<%= render partial: "tags/tag", locals: {tag: tag} %> |
						<% end %>
					</p>
				</li>
<!-- 				<li>
					<h2>Blogroll</h2>
					<ul>
					  <% @todays_posts.each do |p| %>
					    <li><%= link_to p.title, p %></li>
					  <% end %>
					</ul>
				</li> -->
			</ul>
		</div>

		<!-- end #content -->
		<div style="clear: both;">&nbsp;</div>
	</div>
	<!-- end #page -->
</div>
<div id="footer">
	<p>Design by <a href="http://www.freecsstemplates.org/">FCT</a>.</p>
</div>
<!-- end #footer -->
</body>
</html>